name: CxWar
version: "${project.version}"
main: ca.ckay9.CxWar
api-version: 1.19
authors: [CKAY9]
description: "${project.description}"
commands:
    reveal:
        description: Reveal a player's location with your own also being revealed.
    hidden:
        description: Hide from reveals using diamonds or netherite
    group:
        description: Create, join, or leave groups
    cxwar:
        description: Learn about the plugin
    killstreak:
        description: View your own or other's killstreak
    whisper:
        description: Secretly chat with other players
    tpr:
        description: Request to teleport to someone
    tpa:
        description: Accept a teleport request from someone